-- CreateTable
CREATE TABLE "Ad" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "brand" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "body" TEXT NOT NULL,
    "generation" TEXT,
    "engineType" TEXT NOT NULL,
    "driveType" TEXT NOT NULL,
    "transmission" TEXT NOT NULL,
    "engineMod" TEXT NOT NULL,
    "color" TEXT NOT NULL,
    "mileage" INTEGER NOT NULL,
    "options" JSONB NOT NULL,
    "documentType" TEXT NOT NULL,
    "owners" INTEGER NOT NULL,
    "purchaseDate" DATETIME NOT NULL,
    "description" TEXT NOT NULL,
    "contacts" TEXT NOT NULL,
    "inspectionLat" REAL,
    "inspectionLng" REAL,
    "price" REAL NOT NULL,
    "licensePlate" TEXT NOT NULL,
    "vin" TEXT NOT NULL,
    "sts" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "userId" INTEGER NOT NULL
);
